name: air_traffic_data_pipeline
version: 1.0.0
config-version: 2
profile: air-traffic-data-pipeline
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
models:
  air_traffic_data_pipeline:
    +materialized: view
