-- JSON file format
CREATE FILE FORMAT IF NOT EXISTS AIR_TRAFFIC_DB.RAW.JSON_FORMAT
    TYPE = JSON
    STRIP_OUTER_ARRAY = TRUE;

-- Automatic ingestion from AWS S3 to Snowflake
CREATE OR REPLACE PIPE AIR_TRAFFIC_DB.RAW.OPENSKY_PIPE
    AUTO_INGEST = TRUE
AS
COPY INTO AIR_TRAFFIC_DB.RAW.OPENSKY_RAW
FROM @AIR_TRAFFIC_DB.RAW.S3_STAGE
FILE_FORMAT = (
    FORMAT_NAME = 'AIR_TRAFFIC_DB.RAW.JSON_FORMAT'
)
PATTERN = '.*opensky_[0-9]{8}_[0-9]{6}\.json';
