-- Track incoming changes in the raw table
CREATE STREAM IF NOT EXISTS AIR_TRAFFIC_DB.RAW.OPENSKY_RAW_STREAM
    ON TABLE AIR_TRAFFIC_DB.RAW.OPENSKY_RAW;

-- Log processed batches
CREATE TABLE IF NOT EXISTS AIR_TRAFFIC_DB.RAW.PIPELINE_BATCH_LOG (
    processed_at TIMESTAMP_TZ,
    row_count INTEGER
);

-- Consume new stream records when data arrives
CREATE OR REPLACE TASK AIR_TRAFFIC_DB.ANALYTICS.CONSUME_OPENSKY_STREAM
    WAREHOUSE = COMPUTE_WH
    WHEN SYSTEM$STREAM_HAS_DATA(
        'AIR_TRAFFIC_DB.RAW.OPENSKY_RAW_STREAM'
    )
AS
    INSERT INTO AIR_TRAFFIC_DB.RAW.PIPELINE_BATCH_LOG
        (processed_at, row_count)
    SELECT
        CURRENT_TIMESTAMP(),
        COUNT(*)
    FROM AIR_TRAFFIC_DB.RAW.OPENSKY_RAW_STREAM;

-- Run dbt after consuming the stream
CREATE OR REPLACE TASK AIR_TRAFFIC_DB.ANALYTICS.RUN_DBT_ON_NEW_DATA
    WAREHOUSE = COMPUTE_WH
    AFTER AIR_TRAFFIC_DB.ANALYTICS.CONSUME_OPENSKY_STREAM
AS
    EXECUTE DBT PROJECT AIR_TRAFFIC_DB.ANALYTICS.AIR_TRAFFIC_DBT
    ARGS = 'run';

-- Enable the task graph (child first, then root)
ALTER TASK AIR_TRAFFIC_DB.ANALYTICS.RUN_DBT_ON_NEW_DATA RESUME;
ALTER TASK AIR_TRAFFIC_DB.ANALYTICS.CONSUME_OPENSKY_STREAM RESUME;
