-- Database and schemas
CREATE DATABASE IF NOT EXISTS AIR_TRAFFIC_DB;

CREATE SCHEMA IF NOT EXISTS AIR_TRAFFIC_DB.RAW;
CREATE SCHEMA IF NOT EXISTS AIR_TRAFFIC_DB.ANALYTICS;

-- Raw JSON storage
CREATE TABLE IF NOT EXISTS AIR_TRAFFIC_DB.RAW.OPENSKY_RAW (
    DATA VARIANT
);

-- AWS S3 storage integration
-- Replace placeholders with your own AWS configuration.
CREATE STORAGE INTEGRATION IF NOT EXISTS S3_AIR_TRAFFIC_INT
    TYPE = EXTERNAL_STAGE
    STORAGE_PROVIDER = 'S3'
    ENABLED = TRUE
    STORAGE_AWS_ROLE_ARN = '<AWS_IAM_ROLE_ARN>'
    STORAGE_ALLOWED_LOCATIONS = ('s3://<YOUR_BUCKET>/processed/');

-- External S3 stage
CREATE STAGE IF NOT EXISTS AIR_TRAFFIC_DB.RAW.S3_STAGE
    STORAGE_INTEGRATION = S3_AIR_TRAFFIC_INT
    URL = 's3://<YOUR_BUCKET>/processed/';
